export const BUSCARUSUARIO = 'BUSCARUSUARIO'

/*export const TEMPERAMENTO = 'TEMPERAMENTO'
export const FILTROINPUT = 'FILTROINPUT'
export const ORDERAZ = 'ORDERAZ'
export const FILTROTEMPERAMENTO = 'FILTROTEMPERAMENTO'
export const COPYDOG = 'COPYDOG'
export const IDBD = 'IDBD'*/
